import type { CardName } from './types';

export const cardLabels: Record<CardName, string> = {
  sha: '杀',
  shan: '闪',
  tao: '桃',
  wuzhongshengyou: '无中生有',
  guohechaiqiao: '过河拆桥',
  shunshouqianyang: '顺手牵羊',
  jiedaosharen: '借刀杀人',
  nanmanruqin: '南蛮入侵',
  wanjianqifa: '万箭齐发',
  taoyuanjieyi: '桃园结义',
  wugufengdeng: '五谷丰登',
  juedou: '决斗',
  wuxiekeji: '无懈可击',
  lebusishu: '乐不思蜀',
  shandian: '闪电',
  zhugeliannu: '诸葛连弩',
  qinggangjian: '青釭剑',
  cixiongshuanggujian: '雌雄双股剑',
  hanbingjian: '寒冰剑',
  qinglongyanyuedao: '青龙偃月刀',
  zhangbashemao: '丈八蛇矛',
  guanshifu: '贯石斧',
  fangtianhuaji: '方天画戟',
  qilingong: '麒麟弓',
  baguazhen: '八卦阵',
  renwangdun: '仁王盾',
  jueying: '绝影',
  dilu: '的卢',
  zhuahuangfeidian: '爪黄飞电',
  dawan: '大宛',
  chitu: '赤兔',
  zixing: '紫骍'
};
